product:
    resource: "@ProductBundle/Resources/config/routing.yml"
    prefix:   /Products
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /User

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

posts:
    resource: "@PostsBundle/Resources/config/routing.yml"
    prefix:   /Posts

app:
    resource: '@AppBundle/Controller/'
    type: annotation

