news:
    resource: "@NewsBundle/Resources/config/routing.yml"
    prefix:   /Article

forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /Forum

product:
    resource: "@ProductBundle/Resources/config/routing.yml"
    prefix:   /Products
tvshow_reclamationtvshow:
    resource: "@tvshowBundle/Controller/reclamationtvshowController.php"
    type:     annotation

tvshow_ratingtvshow:
    resource: "@tvshowBundle/Controller/ratingtvshowController.php"
    type:     annotation

tvshow_commentairetvshow:
    resource: "@tvshowBundle/Controller/commentairetvshowController.php"
    type:     annotation

tvshow_tvshow:
    resource: "@tvshowBundle/Controller/TvshowController.php"
    type:     annotation

tvshow:
    resource: "@tvshowBundle/Resources/config/routing.yml"
    prefix:   /Tvshow

events:
    resource: "@EventsBundle/Resources/config/routing.yml"
    prefix:   /Events

calendar_message:
    resource: "@CalendarZiedBundle/Controller/MessageController.php"
    type:     annotation

calendar_deals:
    resource: "@CalendarZiedBundle/Controller/dealsController.php"
    type:     annotation

calendar_calendars:
    resource: "@CalendarZiedBundle/Controller/CalendarsController.php"
    type:     annotation

calendarZied:
    resource: "@CalendarZiedBundle/Resources/config/routing.yml"
    prefix:   /calendars

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /User

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

posts:
    resource: "@PostsBundle/Resources/config/routing.yml"
    prefix:   /Posts

app:
    resource: '@AppBundle/Controller/'
    type: annotation

mgilet_notification:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications
adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"


gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


