tvshow_ratingtvshow:
    resource: "@tvshowBundle/Controller/ratingtvshowController.php"
    type:     annotation

tvshow_commentairetvshow:
    resource: "@tvshowBundle/Controller/commentairetvshowController.php"
    type:     annotation

tvshow_tvshow:
    resource: "@tvshowBundle/Controller/TvshowController.php"
    type:     annotation

tvshow:
    resource: "@tvshowBundle/Resources/config/routing.yml"
    prefix:   /Tvshow

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /User

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

posts:
    resource: "@PostsBundle/Resources/config/routing.yml"
    prefix:   /Posts

app:
    resource: '@AppBundle/Controller/'
    type: annotation

