news:
    resource: "@NewsBundle/Resources/config/routing.yml"
    prefix:   /Article

forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /Forum

product:
    resource: "@ProductBundle/Resources/config/routing.yml"
    prefix:   /Products
tvshow_reclamationtvshow:
    resource: "@tvshowBundle/Controller/reclamationtvshowController.php"
    type:     annotation

tvshow_ratingtvshow:
    resource: "@tvshowBundle/Controller/ratingtvshowController.php"
    type:     annotation

tvshow_commentairetvshow:
    resource: "@tvshowBundle/Controller/commentairetvshowController.php"
    type:     annotation

tvshow_tvshow:
    resource: "@tvshowBundle/Controller/TvshowController.php"
    type:     annotation

tvshow:
    resource: "@tvshowBundle/Resources/config/routing.yml"
    prefix:   /Tvshow

events:
    resource: "@EventsBundle/Resources/config/routing.yml"
    prefix:   /Events

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /User

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

posts:
    resource: "@PostsBundle/Resources/config/routing.yml"
    prefix:   /Posts

app:
    resource: '@AppBundle/Controller/'
    type: annotation

mgilet_notification:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications


gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"