calendar_message:
    resource: "@CalendarZiedBundle/Controller/MessageController.php"
    type:     annotation

calendar_deals:
    resource: "@CalendarZiedBundle/Controller/dealsController.php"
    type:     annotation

calendar_calendars:
    resource: "@CalendarZiedBundle/Controller/CalendarsController.php"
    type:     annotation

calendarZied:
    resource: "@CalendarZiedBundle/Resources/config/routing.yml"
    prefix:   /calendars

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /User

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

posts:
    resource: "@PostsBundle/Resources/config/routing.yml"
    prefix:   /Posts

app:
    resource: '@AppBundle/Controller/'
    type: annotation

adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


