<?php

namespace CalendarZiedBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarsRepository extends \Doctrine\ORM\EntityRepository
{
    public function Findbyuser($idu)
    {
        $qb = $this->createQueryBuilder('v')
            ->where('v.idu = :idu')->setParameter('idu', $idu)->getQuery();
        return $qb->getResult();
    }
}
