<?php

namespace CalendarZiedBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DealsRepository extends \Doctrine\ORM\EntityRepository
{
    public function Findbycalendarname($calendarname)
    {
        $qb = $this->createQueryBuilder('v')
            ->where('v.calendarname = :calendarname')->distinct()->setParameter('calendarname', $calendarname)->getQuery();
        return $qb->getResult();
    }

    public function Finddealsbyuser($idu)
    {
        $qb = $this->createQueryBuilder('v')
            ->where('v.idu != :idu')->setParameter('idu', $idu)->getQuery();
        return $qb->getResult();
    }

    public function resizeEvent($idEvent, $startDate, $endDate)
    {
        return $this
            ->createQueryBuilder('e')
            ->update('CalendarZiedBundle:deals', 'e')
            ->set('e.start', '?1')
            ->set('e.end', '?2')
            ->where('e.eventdescription = ?3')
            ->setParameter(1, $startDate)
            ->setParameter(2, $endDate)
            ->setParameter(3, $idEvent)
            ->getQuery()
            ->getResult();
    }

    public function dropEvent($idEvent, $startDate, $endDate)
    {
        return $this
            ->createQueryBuilder('e')
            ->update('CalendarZiedBundle:deals', 'e')
            ->set('e.start', '?1')
            ->set('e.end', '?2')
            ->where('e.eventdescription = ?3')
            ->setParameter(1, $startDate)
            ->setParameter(2, $endDate)
            ->setParameter(3, $idEvent)
            ->getQuery()
            ->getResult();
    }

    public function deleteEvent($idEvent)
    {
        return $this
            ->createQueryBuilder('e')
            ->delete('CalendarZiedBundle:deals', 'e')
            ->where('e.eventdescription = ?1')
            ->setParameter(1, $idEvent)
            ->getQuery()
            ->getResult();
    }


}
