<?php

namespace CalendarZiedBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findmessage($idu)
    {
        return $this->createQueryBuilder('c')
        ->select('c')
        ->where('c.idu=:idu' )
        ->setParameter('idu', $idu)
     ->getQuery()
     ->getResult();
    }

public function findmessage1($idu)
{
    $query=$this->createQueryBuilder('v')
        ->select('v')
        ->join('v.fos_user','t')
        ->where('t.nomT=:film' )
        ->setParameter('film', $idu)
        ->getQuery();
    return $query->getSingleScalarResult();
}

public function messagenotseen($idreceiver)
    {
        $number=1;
        $qb = $this->createQueryBuilder('v')
            ->where('v.seen = :seen')
            ->andWhere('v.idreceiver=:idreceiver')
            ->setParameter('idreceiver', $idreceiver)
            ->setParameter('seen', $number)
            ->getQuery();
        return $qb->getResult();
    }

    public function messagenotseen2($idreceiver)
    {
        $number=1;
        $qb = $this->createQueryBuilder('v')
            ->where('v.seen = :seen')
            ->andWhere('v.idreceiver=:idreceiver')
            ->setParameter('idreceiver', $idreceiver)
            ->setParameter('seen', $number)
            ->getQuery();
        return $qb->getResult();
    }
}
