<?php

namespace NewsBundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function sortbynbvue()
    {
        return $this->createQueryBuilder('r')

            ->select('r.id')
            ->addOrderBy('nbrevue',"desc")
            ->getQuery()
            ->getSingleScalarResult();

    }

}