<?php

namespace NewsBundle\Repository;

/**
 * reviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reviewRepository extends \Doctrine\ORM\EntityRepository
{
    public function avgrating($id)
    {
        return $this->createQueryBuilder('r')

            ->select('avg(r.rate)')
            ->where('r.idarticle=:id' )
            ->setParameter('id', $id)
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function avgstatrating()
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT avg(c.rate),n.nomArticle FROM NewsBundle:review c ,NewsBundle:News n where c.idarticle=n.idArticle group by c.idarticle ");
        return $query->getResult();

     /*   $dql = 'SELECT avg(c.rate),count(c.rate) NewsBundle\Entity\review  c group by c.idarticle';
        $query = $this->getEntityManager()->createQuery($dql);
        return $query->execute();
    */


    }

}
