<?php

namespace NewsBundle\Repository;

/**
 * reviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reviewRepository extends \Doctrine\ORM\EntityRepository
{
    public function avgrating($id)
    {
        return $this->createQueryBuilder('r')

            ->select('avg(r.rate)')
            ->where('r.idarticle=:id' )
            ->setParameter('id', $id)
            ->getQuery()
            ->getSingleScalarResult();
    }
}
