
get_products:
    path:     /getProducts
    defaults: { _controller: ProductBundle:Product:getProducts }

get_product_by_id:
    path:     /getProducts/{id}
    defaults: { _controller: ProductBundle:Product:getProductById }

add_product:
    path:     /addProduct
    defaults: { _controller: ProductBundle:Product:addProduct }

delete_product:
    path:     /deletProduct/{id}/{validation}
    defaults: { _controller: ProductBundle:Product:deleteProduct }

