<?php

namespace tvshowBundle\Repository;

/**
 * commentairetvshowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentairetvshowRepository extends \Doctrine\ORM\EntityRepository
{
    public function nombrecommentaires($id)
    {
        return $this->createQueryBuilder('r')

            ->select('COUNT(r)')
            ->where('r.tvshow=:id' )
            ->setParameter('id', $id)
            ->getQuery()

            ->getSingleScalarResult();
    }
}
