<?php

namespace tvshowBundle\Repository;

/**
 * ratingtvshowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ratingtvshowRepository extends \Doctrine\ORM\EntityRepository
{
    public function nombrerating($id)
    {
        return $this->createQueryBuilder('r')

            ->select('COUNT(r)')
            ->where('r.tvshow=:id' )
            ->setParameter('id', $id)
            ->getQuery()

            ->getSingleScalarResult();
    }
    public function existerating($id,$idu)
    {         $parametres=array('id' => $id , 'idu' => $idu );
        return $this->createQueryBuilder('r')
            ->select('COUNT(r)')
            ->where('r.tvshow=:id' )
            ->andWhere('r.User_id =:idu')
            ->setParameters($parametres)
            ->getQuery()

            ->getSingleScalarResult();
    }
    public function nombrerating1($id)
    {
        return $this->createQueryBuilder('r')

            ->select('COUNT(r)')
            ->where('r.tvshow=:id' )
            ->andWhere('r.rate = 1')
            ->setParameter('id', $id)
            ->getQuery()

            ->getSingleScalarResult();
    }
    public function nombrerating2($id)
    {
        return $this->createQueryBuilder('r')

            ->select('COUNT(r)')
            ->where('r.tvshow=:id' )
            ->andWhere('r.rate = 2')
            ->setParameter('id', $id)
            ->getQuery()

            ->getSingleScalarResult();
    }
    public function nombrerating3($id)
    {
        return $this->createQueryBuilder('r')

            ->select('COUNT(r)')
            ->where('r.tvshow=:id' )
            ->andWhere('r.rate = 3')
            ->setParameter('id', $id)
            ->getQuery()

            ->getSingleScalarResult();
    }
    public function nombrerating4($id)
    {
        return $this->createQueryBuilder('r')

            ->select('COUNT(r)')
            ->where('r.tvshow=:id' )
            ->andWhere('r.rate = 4')
            ->setParameter('id', $id)
            ->getQuery()

            ->getSingleScalarResult();
    }
    public function nombrerating5($id)
    {
        return $this->createQueryBuilder('r')

            ->select('COUNT(r)')
            ->where('r.tvshow=:id' )
            ->andWhere('r.rate = 5')
            ->setParameter('id', $id)
            ->getQuery()

            ->getSingleScalarResult();
    }

    public function sommerating($id)
    {
        return $this->createQueryBuilder('r')

            ->select('SUM(r.rate)')
            ->where('r.tvshow=:id' )
            ->setParameter('id', $id)
            ->getQuery()

            ->getSingleScalarResult();
    }



}
