<?php

namespace tvshowBundle\Repository;

/**
 * reclamationtvshowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reclamationtvshowRepository extends \Doctrine\ORM\EntityRepository
{
}
