<?php


namespace tvshowBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TvshowRepository extends \Doctrine\ORM\EntityRepository
{
    public function findrecherche()
    {

        return $this->createQueryBuilder('t')
            ->select('DISTINCT t.name')

            ->getQuery()

     ->getResult();
    }
    public function nombretvshow()
    {
        return $this->createQueryBuilder('t')

            ->select('COUNT(t)')

            ->getQuery()

            ->getSingleScalarResult();
    }

}