posts_homepage:
    path:     /
    defaults: { _controller: PostsBundle:Default:index }

add_post:
    path:     /AddPost
    defaults: { _controller: PostsBundle:Posts:AddPost }

add_p:
    path:     /AddP/{img}/{des}
    defaults: { _controller: PostsBundle:Posts:AddP }

get_posts:
    path:     /GetPosts
    defaults: { _controller: PostsBundle:Posts:GetPosts }

update_post:
    path:     /UpdatePost/{id}
    defaults: { _controller: PostsBundle:Posts:UpdatePost }

delete_post:
    path:     /RemoveP/{id}
    defaults: { _controller: PostsBundle:Posts:RemoveP }

remove_post:
  path:     /DeletePost/{id}
  defaults: { _controller: PostsBundle:Posts:DeletePost }

react_post:
    path:     /ReactPost/{idp}/{react}
    defaults: { _controller: PostsBundle:Posts:React }

remove_like:
    path:     /RemoveLike/{id}
    defaults: { _controller: PostsBundle:Posts:RemoveLike }

add_comment:
    path:     /AddComment/{id}/{contenu}
    defaults: { _controller: PostsBundle:Posts:AddComment }

get_comments:
    path:     /GetComments/{id}
    defaults: { _controller: PostsBundle:Comments:GetComments }

delete_comment:
    path:     /DeleteComment/Post={id}/Comment={idc}
    defaults: { _controller: PostsBundle:Comments:DeleteComment }

update_comment:
    path:     /UpdateComment/Post={id}/Comment={idc}
    defaults: { _controller: PostsBundle:Comments:UpdateComment }

single_post:
    path:     /SinglePost/{id}
    defaults: { _controller: PostsBundle:Posts:SinglePost }


