forum_homepage:
    path:     /
    defaults: { _controller: ForumBundle:Default:index }

publications:
    path:     /ajoutersujet
    defaults: { _controller: ForumBundle:Forum:ajoutersujet }
afficher_messujets:
    path:     /afficherforums
    defaults: { _controller: ForumBundle:Forum:mesForums }
supprimer_sujet:
    path:     /supprimersujey/{id}
    defaults: { _controller: ForumBundle:Forum:supprimerSujet }
modifier_sujet:
    path:     /modifiersujet/{id}
    defaults: { _controller: ForumBundle:Forum:modifierSujet }
list_forum:
    path:     /listforum
    defaults: { _controller: ForumBundle:Forum:affichageforum }
back_forum:
    path:     /backforum
    defaults: { _controller: ForumBundle:Forum:reloadback  }

validersujet:
    path:     /{id}/validerSujet
    defaults: { _controller: ForumBundle:Forum:validersujet }

refusersujet:
    path:     /{id}/refuserSujet
    defaults: { _controller: ForumBundle:Forum:refusersujet }
detail_sujet:
    path:     /detailssujet/{id}
    defaults: { _controller: ForumBundle:Forum:detailssujet }
like:
    path:     /like/{id}
    defaults: { _controller: ForumBundle:Forum:like }
modifier_comment:
    path:     /modifiercomment/{id}
    defaults: { _controller: ForumBundle:Forum:modifierComment }
supprimer_comment:
    path:     /supprimercomment/{id}
    defaults: { _controller: ForumBundle:Forum:supprimerComment }
aman:
    path:     /aman/{id}
    defaults: { _controller: ForumBundle:Forum:aman }
chart:
    path:     /chart
    defaults: { _controller: ForumBundle:Forum:chart }
signaler:
    path:     /signaler/{id}
    defaults: { _controller: ForumBundle:Forum:signaler }
signalerback:
    path:     /signalerback
    defaults: { _controller: ForumBundle:Forum:signalerback }
supprimersujetsignaler:
    path:     /supprimersujetsignaler/{id}
    defaults: { _controller: ForumBundle:Forum:supprimersujetsignaler }
historique:
    path:     /historique
    defaults: { _controller: ForumBundle:Forum:afficherhistorique }
clearhistory:
    path:     /clear
    defaults: { _controller: ForumBundle:Forum:deletehistorique }


toussujetsM:
    path:     /toussujetsM
    defaults: { _controller: ForumBundle:Forum:toussujetsM }







messujetsM:
    path:     /messujetsM/{id}
    defaults: { _controller: ForumBundle:Forum:messujetsM }
CommentairedusujetM:
    path:     /CommentairedusujetM/{idu}/{id}
    defaults: { _controller: ForumBundle:Forum:CommentairedusujetM }
sujetcommentM:
    path:     /sujetcommentM/{id}
    defaults: { _controller: ForumBundle:Forum:sujetetcommentaireM }
supprimersujetM:
    path:     /supprimersujetM/{id}
    defaults: { _controller: ForumBundle:Forum:supprimersujetM }
supprimercommentaireM:
    path:     /supprimercommentaireM/{id}
    defaults: { _controller: ForumBundle:Forum:supprimercommentaireM }
updatesujetM:
    path:     /updatesujetM/{id}/{description}
    defaults: { _controller: ForumBundle:Forum:updatesujetM }
updatecommentaireM:
    path:     /updatecommentaireM/{id}
    defaults: { _controller: ForumBundle:Forum:updatecommentaireM }
ajoutersujetM:
    path:     /ajoutersujetM/{idu}/{description}
    defaults: { _controller: ForumBundle:Forum:ajoutersujetM }
ajoutercommentaireM:
    path:     /ajoutercommentaireM/{id}
    defaults: { _controller: ForumBundle:Forum:ajoutercommentaireM }
subjectidM:
    path:     /subjectidM/{id}
    defaults: { _controller: ForumBundle:Forum:subjectidM }
top5sujetM:
    path:     /top5sujetM
    defaults: { _controller: ForumBundle:Forum:top5sujetM }
tousM:
    path:     /tousM
    defaults: { _controller: ForumBundle:Forum:tousM }
affichicommentaireM:
    path:     /affichicommentaireM/{id}
    defaults: { _controller: ForumBundle:Forum:affichicommentaireM }
likem:
    path:     /likem/{id}
    defaults: { _controller: ForumBundle:Forum:likem }


