<?php

namespace PostsBundle\Repository;

use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * PostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostsRepository extends \Doctrine\ORM\EntityRepository
{

    public function VerifUserLiked($idPost,$idu)
    {

        $query = $this->getEntityManager()
            ->createQuery("SELECT COUNT(l) FROM PostsBundle:Likes l WHERE l.idu ='$idu' AND l.idpost = '$idPost' ");
        try {
            return $query->getSingleScalarResult();
        } catch (NoResultException $e) {
        } catch (NonUniqueResultException $e) {
        }
    }

    public function GetPostLike($idPost,$idu)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT l FROM PostsBundle:Likes l WHERE l.idu ='$idu' AND l.idpost = '$idPost' ");

        try {
            return $query->getSingleResult();
        } catch (NoResultException $e) {
        } catch (NonUniqueResultException $e) {
        }


    }
}