<?php

namespace PostsBundle\Repository;

/**
 * StoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoriesRepository extends \Doctrine\ORM\EntityRepository
{
}
