<?php

namespace PostsBundle\Repository;

/**
 * ViewerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewerRepository extends \Doctrine\ORM\EntityRepository
{
}
