<?php

namespace ForumBundle\Repository;

/**
 * FavorisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavorisRepository extends \Doctrine\ORM\EntityRepository
{
    public function desc($id)
    {

        $query = $this->getEntityManager()->createQuery("Select p.descriptionf FROM ForumBundle\Entity\Favoris p where p.id=:id")
        ->setParameter('id',$id);

        return $query->getResult();




    }
}
