<?php

namespace ForumBundle\Repository;

/**
 * signalerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class signalerRepository extends \Doctrine\ORM\EntityRepository
{


}
