news_homepage:
    path:     /
    defaults: { _controller: NewsBundle:Default:index }
showArticle:
    path:     /showArticle
    defaults: { _controller: NewsBundle:News:showArticle }
ajoutArticle:
    path:     /ajoutArticle
    defaults: { _controller: NewsBundle:News:newArticle }
articleDelete:
    path:     /deleteArticle/{id}
    defaults: { _controller: NewsBundle:News:deleteArticle }
articleUpdate:
    path:     /editArticle/{id}
    defaults: { _controller: NewsBundle:News:editArticle }
showArticleFront:
    path:     /showArticlefront
    defaults: { _controller: NewsBundle:News:showArticlefront }
    methods : [GET]
article:
    path:     /article/{id}
    defaults: { _controller: NewsBundle:News:article }
imprimer:
    path:     /imprimer/{id}
    defaults: { _controller: NewsBundle:News:imprimer }
showreview:
    path:     /showreview/{id}
    defaults: { _controller: NewsBundle:News:showreview }
trinbvue:
    path:     /trinbvue
    defaults: { _controller: NewsBundle:News:trinbvue }
    methods : [GET]
plusrecent:
    path:     /plusrecent
    defaults: { _controller: NewsBundle:News:triplusrecent }
moinsrecent:
    path:     /moinsrecent
    defaults: { _controller: NewsBundle:News:trimoinsrecent }
statrating:
    path:     /chartrating
    defaults: { _controller: NewsBundle:News:chartrating }



newM:
    path:     /newM
    defaults: { _controller: NewsBundle:News:newM }

supprimerArticle:
    path:     /supprimerArticle/{id}
    defaults: { _controller: NewsBundle:News:supprimerArticle }
findarticle:
    path:     /findarticle/{nomArticle}
    defaults: { _controller: NewsBundle:News:findarticle }
allArticle:
    path:     /allArticle
    defaults: { _controller: NewsBundle:News:allarticle }

oneArticle:
    path:     /oneArticle/{id}
    defaults: { _controller: NewsBundle:News:oneArticle }
updateArticle:
    path:     /updateArticle/{id}
    defaults: { _controller: NewsBundle:News:updateArticle }







nbvue:
    path:     /nbvue/{id}
    defaults: { _controller: NewsBundle:News:nbvue }

supparticle:
    path:     /supparticle/{id}
    defaults: { _controller: NewsBundle:News:supparticle }
rateM:
    path:     /rateM/{rate}/{idu}/{ida}
    defaults: { _controller: NewsBundle:News:rateM }
Statmobile:
    path:     /Statmobile
    defaults: { _controller: NewsBundle:News:Statmobile }
Statmobile1:
    path:     /Statmobile1
    defaults: { _controller: NewsBundle:News:Statmobile1 }
Statmobile2:
    path:     /Statmobile2
    defaults: { _controller: NewsBundle:News:Statmobile2 }
imprimerM:
    path:     /imprimerM/{id}
    defaults: { _controller: NewsBundle:News:imprimerM }
ratemoyenneM:
    path:     /ratemoyenneM/{id}
    defaults: { _controller: NewsBundle:News:ratemoyenneM }