news_homepage:
    path:     /
    defaults: { _controller: NewsBundle:Default:index }
showArticle:
    path:     /showArticle
    defaults: { _controller: NewsBundle:News:showArticle }
ajoutArticle:
    path:     /ajoutArticle
    defaults: { _controller: NewsBundle:News:newArticle }
articleDelete:
    path:     /deleteArticle/{id}
    defaults: { _controller: NewsBundle:News:deleteArticle }
articleUpdate:
    path:     /editArticle/{id}
    defaults: { _controller: NewsBundle:News:editArticle }
showArticleFront:
    path:     /showArticlefront
    defaults: { _controller: NewsBundle:News:showArticlefront }
    methods : [GET]
article:
    path:     /article/{id}
    defaults: { _controller: NewsBundle:News:article }
imprimer:
    path:     /imprimer/{id}
    defaults: { _controller: NewsBundle:News:imprimer }
showreview:
    path:     /showreview/{id}
    defaults: { _controller: NewsBundle:News:showreview }
trinbvue:
    path:     /trinbvue
    defaults: { _controller: NewsBundle:News:trinbvue }
    methods : [GET]
plusrecent:
    path:     /plusrecent
    defaults: { _controller: NewsBundle:News:triplusrecent }
moinsrecent:
    path:     /moinsrecent
    defaults: { _controller: NewsBundle:News:trimoinsrecent }
statrating:
    path:     /chartrating
    defaults: { _controller: NewsBundle:News:chartrating }